repos:
  -   repo: https://github.com/ambv/black
      rev: 25.1.0
      hooks:
        - id: black
          language_version: python3
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.7
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  -   repo: https://github.com/pycqa/isort
      rev: 6.0.1
      hooks:
        - id: isort
